### ISSUE TITLE
publication page generator

### ISSUE THREAD

**Issue by lexingxie** [lexingxie/cmLab#3]
the envisioned workflow is:

bibtext --> json object in python (or something similar) --> markdown fragments --> publications.md (w. front matter added) 

* this needs to support hyperlinking of pdf, abstract, bibtex, talk slides, and project pages (these are recorded in the bibtex) 
* the publications can be sorted by year
* the tool for the first step can be: 
https://bibtexparser.readthedocs.org/en/v0.6.2/tutorial.html

**Comment by andrei-rizoiu** [comment]
[The service bibbase.org](http://bibbase.org/) seems to be doing exactly what we want. It simply requires a publicly accessible **bib** file and generates the visualization. It extends the bib format with another 3 URL fields, which allows to put the paper for download, presentation etc ([details here](http://bibbase.org/help)).

**Pros:** Embedding in webpage is extremely easy and it adapts to the style. Does everything we want to do.

**Cons:** links don't seem to be click-able directly (need to open explicitly in new tab). This behavior appears consistently to provided examples and deployed pages (see [this example](http://www.cs.toronto.edu/kr/) for a production page at the University of Toronto).

**Comment by lexingxie** [comment]
I pushed the changes to the cecs server, and bibBase doesn't seem to work! 
http://cm.cecs.anu.edu.au/publications/

**Comment by lexingxie** [comment]
btw, having to push to CECS server before testing the .bib file is too long of a debugging cycle. 
the bib file is available here
https://raw.githubusercontent.com/lexingxie/cmLab/master/static/documents/publications.bib

and I've made a test page to use this version (pubs_preview/  draft=true in the front matter), 
compile+preview with hugo server -D --watch

**Comment by almath123** [comment]
Do we have a solution for testing the publications.bib file yet? Testing on production seems like a very bad idea.

Personally I think it might be too much effort to go from a bib file to html, why not just have a manually built list? It would actually be easier to maintain than the current system.

Thoughts?

**Comment by andrei-rizoiu** [comment]
I fear that a manually-kept list will be an increasing pain to maintain. A single bibfile has the advantage of just an initial learning step.

You can check and test the single bibfile approach using this steps:
- fork the main repo;
- find out the address of the bibfile in your repo: e.g. in the main repo it is at: 
https://raw.githubusercontent.com/lexingxie/cmLab/master/static/documents/publications.bib
- navigate to bibbase.org and generate the list using that address.
i.e. for the main repo, it will be at: http://bibbase.org/show?bib=https%3A%2F%2Fraw.githubusercontent.com%2Flexingxie%2FcmLab%2Fmaster%2Fstatic%2Fdocuments%2Fpublications.bib&msg=embed
- finally obtain the embedding code and put it in your own page and use it to test it.
e.g. for the main repo it is:
<script src="http://bibbase.org/show?bib=https%3A%2F%2Fraw.githubusercontent.com%2Flexingxie%2FcmLab%2Fmaster%2Fstatic%2Fdocuments%2Fpublications.bib&jsonp=1"></script>

**Comment by lexingxie** [comment]
as discussed in the group meeting, we're keeping the bib-generated publication page -- with a potentially different bib-->html renderer. 

ways to debug your update to publications.bib:

* open pub_preview.md
* update the src link to your own fork of the github repo
* enable compilation of drafts, e.g. hugo server -D  to see the pub_preview rendered. 

now check that the rendered HTML is what you want, commit and send pull request.

**Comment by andrei-rizoiu** [comment]
While not perfect, the BibBase solution seems sufficient for now.
Re-open if troubles arise.
