### ISSUE TITLE
Building error when using the latest version of hugo

### ISSUE THREAD

**Issue by qykong** [lexingxie/cmLab#54]
In the file layouts/partials/footer.copyright.html, the function `.Now.Format` is obsolete and should be replaced by `now.Format`.
However, updating this will cause building errors for old hugo version, so shall we update the function to the latest one or stick to the old version of hugo?

**Comment by lexingxie** [comment]
hugo-update-caused-incompatibility happened once before. 
seems this is a time to force myself (and everyone else, tsk tsk) to use the new version of Hugo? 
seems not too onerous, esp when there's ready-made binary that we can just download?

cheers,
