### ISSUE TITLE
disqus integration

### ISSUE THREAD

**Issue by lexingxie** [lexingxie/cmLab#6]
It seems useful to include functions for discussion on the research pages. 

one widely used service is  https://disqus.com/
and how to do this in hugo https://gohugo.io/extras/comments/

I'd like to call for help to implement this. thoughts? volunteers?

**Comment by andrei-rizoiu** [comment]
Thank you Siqi for adding this feature. It should be running now.
Need some testing, once the feature is pushed on the main site.

**Comment by andrei-rizoiu** [comment]
In production for a while, seems to work adequately.
